### ISSUE TITLE
Setting Hibernate

### ISSUE THREAD

**Issue by camyllaoliveira** [AndressaM/ModuloFeed#6]
- [x] Download do Hibernate e descompactação dos JAR’s
- [x] Configurar o Logger
- [x] Download conetctor MySQL
- [x] Criação de um projeto teste no Eclipse
- [x] Adição dos jar’s no BuildPath do Eclipse
- [x] Configurar o log4j
- [x] Criação de uma entidade para ser persistida
- [x] Configurar as propriedades do Hibernate/JPA
- [x] Teste final

**Comment by isc77** [comment]
- [x] Download do Hibernate e descompactação dos JAR’s
- [x] Configurar o Logger
- [x] Download conetctor MySQL
- [x] Criação de um projeto teste no Eclipse
- [x] Adição dos jar’s no BuildPath do Eclipse
- [x] Configurar o log4j
- [x] Criação de uma entidade para ser persistida
- [x] Configurar as propriedades do Hibernate/JPA
- [x] Teste final

**Comment by AndressaM** [comment]
The last commit , this inssues was done! And the mechanism persistence was created the package(DAO).
